### ISSUE TITLE
E2E tests are broken fixed on high priority.

### ISSUE THREAD

**Issue by sk-enya** [bobanetwork/gateway#256]
## Issue Type

[x] bug report
[ ] feature request

## Current Behavior

E2E tests are broken fixed on high priority.

https://github.com/bobanetwork/gateway/actions/runs/7274524865/job/19820629808?pr=255

## Steps to Reproduce

```
5) Testing General Bridging flow on Goerli
       Should switch to L2:
     CypressError: Timed out retrying after 30050ms: `cy.click()` failed because this element:

`<div id="switchBridgeDirection" class="sc-gVJvzJ fFpsOM">...</div>`

is being covered by another element:

`<div role="presentation" aria-labelledby="transition-modal-title" aria-describedby="transition-modal-description" data-testid="" class="MuiModal-root sc-dlWCHZ kRAoCe">...</div>`

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at ensureIsDescendent (http://localhost:3000/__cypress/runner/cypress_runner.js:139711:76)
      at ensureDescendents (http://localhost:3000/__cypress/runner/cypress_runner.js:139762:5)
      at ensureDescendentsAndScroll (http://localhost:3000/__cypress/runner/cypress_runner.js:139768:14)
      at ensureElIsNotCovered (http://localhost:3000/__cypress/runner/cypress_runner.js:139899:5)
      at runAllChecks (http://localhost:3000/__cypress/runner/cypress_runner.js:140079:52)
      at retryActionability (http://localhost:3000/__cypress/runner/cypress_runner.js:140116:16)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise.attempt.Promise.try (http://localhost:3000/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:3000/__cypress/runner/cypress_runner.js:156356:65)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:155797:14)
      at tryCatcher (http://localhost:3000/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:3000/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:3000/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:3000/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:3000/__cypress/runner/cypress_runner.js:16[861](https://github.com/bobanetwork/gateway/actions/runs/7274524865/job/19820629808?pr=255#step:8:862):18)
      at Promise._fulfill (http://localhost:3000/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:3000/__cypress/runner/cypress_runner.js:18419:46)
  From Your Spec Code:
      at Bridge.switchBridgeDirection (webpack:///./cypress/e2e/helpers/bridge.ts:33:0)
      at Context.eval (webpack:///./cypress/e2e/specs/flow/bridging.spec.cy.ts:26:0)

```

**Comment by sk-enya** [comment]
Already fixed!
